sistema AAPM Senai/sistema AAPM Senai/Controllers/FuncionarioController.cs
using sistema_AAPM_Senai.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sistema_AAPM_Senai.Controllers
{
    public class FuncionarioController : Controller
    {
        static SqlConnection con = new SqlConnection("Server=ESN509VMSSQL;DataBase=TCCjpg;User id=aluno;Password=Senai1234");
        // GET: Funcionario
        public ActionResult Funcionario()
        {
            return View();
        }
        public ActionResult listaAlunos()
        {
            return View(Usuario.ListaAlunos());
        }
        public ActionResult listaProdutos()
        {
            return View(Produtos.ListaProdutos());
        }
        /******************* cadastro de Alunos *********************/
        public ActionResult CadastroAlunos()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CadastroAlunos(int cod_usuario, string email, string tipo_usuario, string senha, string rua, string cidade, string bairro, string nome, int cod_escola, int numero, int ddd)
        {
            Usuario u = new Usuario();
            u.Cod_usuario = cod_usuario;
            u.Email = email;
            u.Tipo_usuario = "Aluno";
            u.Senha = senha;
            u.Rua = rua;
            u.Cidade = cidade;
            u.Bairro = bairro;
            u.Nome = nome;
            u.Cod_escola = cod_escola;
            u.Cargo = 2;
            u.Numero = numero;
            u.Ddd = ddd;

            TempData["Msg"] = u.CadastroFuncionarios();
            return RedirectToAction("cadastroAlunos");
        }

        /******************* edição de Alunos *********************/
        public ActionResult editarAlunos(int id)
        {
            Usuario u = Usuario.BuscaUsuario(id);

            if (u == null)
            {
                TempData["Msg"] = "Erro ao buscar produto!";

                return RedirectToAction("listaAlunos");
            }
            return View(u);
        }

        [HttpPost]
        public ActionResult editarAlunos(int cod_usuario, string email, string tipo_usuario,
            string senha, string rua, string cidade, string bairro, string nome, int cod_escola, int cargo, int numero, int ddd)
        {
            Usuario u = new Usuario();
            u.Cod_usuario = cod_usuario;
            u.Email = email;
            u.Tipo_usuario = tipo_usuario;
            u.Senha = senha;
            u.Rua = rua;
            u.Cidade = cidade;
            u.Bairro = bairro;
            u.Nome = nome;
            u.Cod_escola = cod_escola;
            u.Cargo = cargo;
            u.Numero = numero;
            u.Ddd = ddd;

            string res = u.Editar();

            TempData["Msg"] = res;

            if (res == "Salvo com sucesso!")

                return RedirectToAction("listaAlunos");
            else
                return View();
        }

        /******************* exclusão de Alunos *********************/
        public ActionResult deletarAlunos(int id)
        {
            Usuario u = new Usuario();

            u.Cod_usuario = id;
            TempData["Msg"] = u.Remover();

            return RedirectToAction("listaAlunos");
        }

        /******************* detalhes de Alunos *********************/
        public ActionResult detalhesAlunos(string id)
        {
            Usuario co = Usuario.detalhes(id);

            if (co == null)
            {
                TempData["Msg"] = "Erro ao buscar produto!";

                return RedirectToAction("listaAlunos");
            }
            return View(co);
        }

        /******************* Cadastro de Proodutos *********************/
        public ActionResult cadastroProdutos()
        {
            return View();
        }

        [HttpPost]
        public ActionResult cadastroProdutos(int cod_produto, string preco, string nome_produto, int qtd, int cod_escola)
        {
            foreach (string nomeArquivo in Request.Files)
            {
                HttpPostedFileBase arqPostado = Request.Files[nomeArquivo];
                int tamConteudo = arqPostado.ContentLength; //pega tamanho
                string tipoArq = arqPostado.ContentType; //pega o tipo

                //converter para bytes
                byte[] imgBytes = new byte[tamConteudo];
                arqPostado.InputStream.Read(imgBytes, 0, tamConteudo);

                con.Open();
                SqlCommand qry = new SqlCommand
                    ("INSERT INTO Img(Imagem) VALUES(@imagem)", con);
                qry.Parameters.AddWithValue("@imagem", imgBytes);

                //qry.ExecuteNonQuery();
                con.Close();


                Produtos p = new Produtos();


                p.Cod_produto = cod_produto;
                p.Preco = preco;
                p.Nome_produto = nome_produto;
                p.Qtd = qtd;
                p.Cod_escola = cod_escola;
                p.Imagem = imgBytes;


                TempData["Msg"] = p.cadastroProdutos();


                return RedirectToAction("cadastroProdutos");

            }

            return RedirectToAction("cadastroProdutos");
        }
        /******************* edição de Produtos *********************/
        public ActionResult editarProdutos(int id)
        {
            Produtos u = Produtos.BuscaProdutos(id);

            if (u == null)
            {
                TempData["Msg"] = "Erro ao buscar produto!";

                return RedirectToAction("listaAlunos");
            }
            return View(u);
        }

        [HttpPost]
        public ActionResult editarProdutos(int cod_produto, string preco, string nome_produto, int qtd, int cod_escola)
        {
            Produtos p = new Produtos();


            p.Cod_produto = cod_produto;
            p.Preco = preco;
            p.Nome_produto = nome_produto;
            p.Qtd = qtd;
            p.Cod_escola = cod_escola;

            string res = p.Editar();

            TempData["Msg"] = res;

            if (res == "Salvo com sucesso!")

                return RedirectToAction("listaProdutos");
            else
                return View();
        }

        /******************* exclusão de Produtos *********************/
        public ActionResult deletarProdutos(int id)
        {
            Produtos u = new Produtos();

            u.Cod_produto = id;
            TempData["Msg"] = u.Remover();

            return RedirectToAction("listaProdutos");
        }

        /******************* detalhes dos Produtos *********************/
        public ActionResult detalhesProdutos(string id)
        {
            Produtos co = Produtos.detalhesProdutos(id);

            if (co == null)
            {
                TempData["Msg"] = "Erro ao buscar produto!";

                return RedirectToAction("listaProdutos");
            }
            return View(co);

        }

    }
}

sistema AAPM Senai/sistema AAPM Senai/Views/Funcionario/cadastroProdutos.cshtml
@model sistema_AAPM_Senai.Models.Produtos

@{
    ViewBag.Title = "cadastroProdutos";
}

<h2>cadastroProdutos</h2>

@using (Html.BeginForm("cadastroProdutos", "Funcionario", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produtos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cod_produto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cod_produto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cod_produto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cod_escola, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cod_escola, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cod_escola, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome_produto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome_produto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome_produto, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <form action="~/Funcionario/cadastroProdutos" method="post" enctype="multipart/form-data">
                    <p> Insira a imagem</p>
                    <input type="file" name="img">
                </form>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enviar" class="btn btn-default" />
            </div>
        </div>
    </div>
        }

        <div>
            @Html.ActionLink("Back to List", "listaProdutos")
        </div>

sistema AAPM Senai/sistema AAPM Senai/Views/Funcionario/detalhesProdutos.cshtml
@model sistema_AAPM_Senai.Models.Produtos

@{
    ViewBag.Title = "detalhesProdutos";
}

<h2>detalhesProdutos</h2>

<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cod_produto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cod_produto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qtd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qtd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cod_escola)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cod_escola)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_produto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_produto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

sistema AAPM Senai/sistema AAPM Senai/Views/Funcionario/editarProdutos.cshtml
@model sistema_AAPM_Senai.Models.Produtos

@{
    ViewBag.Title = "editarProdutos";
}

<h2>editarProdutos</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produtos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cod_produto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cod_produto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cod_produto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cod_escola, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cod_escola, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cod_escola, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome_produto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome_produto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome_produto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

sistema AAPM Senai/sistema AAPM Senai/Views/Funcionario/listaAlunos.cshtml
@model IEnumerable<sistema_AAPM_Senai.Models.Usuario>

@{
    ViewBag.Title = "listaAlunos";
}
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="~/images/favicon.ico" />
    <!-- Bootstrap CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="~/css/font-awesome.min.css">

    <!-- ElegantFonts CSS -->
    <link rel="stylesheet" href="~/css/elegant-fonts.css">

    <!-- themify-icons CSS -->
    <link rel="stylesheet" href="~/css/themify-icons.css">

    <!-- Swiper CSS -->
    <link rel="stylesheet" href="~/css/swiper.min.css">
    <!-- Styles -->
    <link href="~/css/style.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/style.css">*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            // Add smooth scrolling to all links
            $("a").on('click', function (event) {

                // Make sure this.hash has a value before overriding default behavior
                if (this.hash !== "") {
                    // Prevent default anchor click behavior
                    event.preventDefault();

                    // Store hash
                    var hash = this.hash;

                    // Using jQuery's animate() method to add smooth page scroll
                    // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 800, function () {

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    });
                } // End if
            });
        });
    </script>
</head>
<body>
    <header class="site-header">

        <div class="nav-bar" id="section1" style="height:79px">
            <div class="container" style="height:70px">
                <div class="row" style="height:55px">
                    <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                        <div class="site-branding d-flex align-items-center">
                            <a class="d-block" href="~/Principal/Principal" rel="home"><img class="d-block" src="~/images/aapm.png" alt="logo"></a>
                        </div><!-- .site-branding -->

                        <nav class="site-navigation d-flex justify-content-end align-items-center">
                            <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-content-center">
                                @*<li><a href="~/Adm/CadastroFuncionarios" style="height:10px">Funcionários</a></li>
                                    <li><a href="~/Adm/CadastroAAPM" style="height:10px">AAPM </a></li>*@
                                <li><a id="myBtn1">Alunos</a></li>

                                <!-- The Modal -->
                                <div id="myModal1" class="modal">

                                    <!-- Modal content -->
                                    <div class="modal-content">
                                        <span class="close">&times;</span>
                                        <center>
                                            <p>Escolha uma opção</p>
                                            <a href="~/Funcionario/cadastroAlunos"><button class="btn btn-default">CADASTRAR ALUNOS</button></a>
                                            <br /><br />
                                            <a href="~/Funcionario/listaAlunos"><button class="btn btn-default">VER ALUNOS</button></a>
                                        </center>
                                    </div>

                                </div>

                                <script>
                                    // Get the modal
                                    var modal = document.getElementById('myModal1');

                                    // Get the button that opens the modal
                                    var btn = document.getElementById("myBtn1");

                                    // Get the <span> element that closes the modal
                                    var span = document.getElementsByClassName("close")[0];

                                    // When the user clicks the button, open the modal
                                    btn.onclick = function () {
                                        modal.style.display = "block";
                                    }

                                    // When the user clicks on <span> (x), close the modal
                                    span.onclick = function () {
                                        modal.style.display = "none";
                                    }

                                    // When the user clicks anywhere outside of the modal, close it
                                    window.onclick = function (event) {
                                        if (event.target == modal) {
                                            modal.style.display = "none";
                                        }
                                    }
                                </script>

                                <li><a id="myBtn2">Produtos</a></li>
                                <!-- The Modal -->
                                <div id="myModal2" class="modal">

                                    <!-- Modal content -->
                                    <div class="modal-content">
                                        <span class="close2">&times;</span>
                                        <center>
                                            <p>Escolha uma opção</p>
                                            <a href="~/Adm/cadastroAAPM"><button>CADASTRAR PRODUTOS</button></a>
                                            <br /><br />
                                            <a href="~/Adm/listaAAPM"><button>VER PRODUTOS</button></a>
                                        </center>
                                    </div>

                                </div>

                                <script>
                                    // Get the modal
                                    var modal2 = document.getElementById('myModal2');

                                    // Get the button that opens the modal
                                    var btn2 = document.getElementById("myBtn2");

                                    // Get the <span> element that closes the modal
                                    var span2 = document.getElementsByClassName("close2")[0];

                                    // When the user clicks the button, open the modal
                                    btn2.onclick = function () {
                                        modal2.style.display = "block";
                                    }

                                    // When the user clicks on <span> (x), close the modal
                                    span2.onclick = function () {
                                        modal2.style.display = "none";
                                    }

                                    // When the user clicks anywhere outside of the modal, close it
                                    window.onclick = function (event) {
                                        if (event.target == modal) {
                                            modal2.style.display = "none";
                                        }
                                    }
                                </script>
                                }
                                }

                            </ul>
                        </nav><!-- .site-navigation -->

                        <div class="hamburger-menu d-lg-none">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div><!-- .hamburger-menu -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .nav-bar -->
    </header><!-- .site-header -->
    <div class="swiper-wrapper">
        <div class="swiper-slide hero-content-wrap" style="height:560px;">
            <img src="~/images/principal.png" alt="">

            <div class="hero-content-overlay position-absolute w-100 h-100">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 col-lg-8 d-flex flex-column justify-content-center align-items-start">
                            <header class="entry-header">

                                <h4>Sistema de gerenciamento</h4>
                                <center>
                                    <h1>da AAPM</h1>
                                </center>

                            </header><!-- .entry-header -->

                            <div class="entry-content mt-4">
                                <div style="width:790px;height:180px;">
                                    <center>
                                        <p></p>
                                        <a href="#section2"><img src="~/images/Seta-dir.png" style="width:100px; height:100px;" /></a>
                                    </center>
                                </div>
                            </div><!-- .entry-content -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .hero-content-overlay -->
        </div><!-- .hero-content-wrap -->
    </div><!-- .swiper-wrapper -->
    <br />
    <p style="text-align:center;">
        @*@Html.ActionLink("Cadastrar novo", "Create")*@
        <center>
            <table class="table" style="width: 1400px;" id="section2">
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Código do usuário
                    </th>
                    <th>
                        Senha
                    </th>
                    <th>
                        Tipo de usuário
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cod_usuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Senha)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tipo_usuario)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "editarAlunos", new { id = item.Cod_usuario }) |
                            @Html.ActionLink("Detalhes", "detalhesAlunos", new { id = item.Cod_usuario }) |
                            @Html.ActionLink("Deletar", "deletarAlunos", new { id = item.Cod_usuario })
                        </td>
                    </tr>
                }
            </table>
            <br /><br />
            <center><a href="~/Funcionario/cadastroAlunos"><button class="btn btn-default">Cadastrar novo</button></a></center>
            <br />
        </center>
</body>
</html>